spring.application.name=fleet_management_backend

spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_db
spring.datasource.username=fleet
spring.datasource.password=fleet
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

app.bootstrap.admin.enabled=true
app.bootstrap.admin.email=admin@fleet.com
app.bootstrap.admin.password=admin

app.jwt.secret=CHANGE_ME_TO_A_LONG_RANDOM_SECRET_32+_CHARS
app.jwt.expiration-ms=86400000

logging.level.org.springframework.security=DEBUG


# OpenAPI docs path
springdoc.api-docs.path=/v3/api-docs

# Swagger UI path
springdoc.swagger-ui.path=/swagger-ui

